oc_user:
    resource: "@OCUserBundle/Controller/"
    type:     annotation
    prefix:   /

mp_platform:
    resource: "@MPPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /login
    defaults:
        _controller: OCUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"