security:
  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER]
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    OCUserBundle\Entity\User: plaintext

  providers:
    in_memory:
      memory:
        users:
          user:  { password: userpass, roles: [ 'ROLE_USER' ] }
          admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

  provider:     in_memory

  firewalls:
      main_login:
          pattern:   ^/login$
          anonymous: true
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      main:
        pattern:      ^/
        anonymous:    true
        form_login:
          login_path: login
          check_path: login_check
        logout:
          path:       logout
          target:     login

  access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }